services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - GUNICORN_CMD_ARGS=--workers=6 --threads=4 --worker-class=gthread
      - SQLITE_CACHE_SIZE=-100000  # 100MB cache
    expose:
      - 5000
    volumes:
      - ./backend/user_data:/app/user_data
      - ./backend/simulados:/app/simulados:ro
    networks:
      - simulados_net
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/simulados"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: fholzer/nginx-brotli:latest
    restart: unless-stopped
    ports:
      - "10443:443/udp"
      - "10443:443"
      - "10080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/nginx/auth/.htpasswd:/etc/nginx/auth/.htpasswd:ro
      - nginx_ssl:/etc/nginx/ssl
      - nginx_cache:/var/cache/nginx
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    entrypoint: /bin/sh
    command: -c "
        apk add --no-cache openssl curl &&
        if [ ! -f /etc/nginx/ssl/privkey.pem ]; then
          echo 'Gerando certificados SSL autoassinados...';
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/privkey.pem -out /etc/nginx/ssl/fullchain.pem -subj '/CN=localhost';
          echo 'Certificados gerados com sucesso.';
        else
          echo 'Certificados SSL já existem.';
        fi &&
        nginx -g 'daemon off;'
      "
    networks:
      - simulados_net
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  redis:
    image: redis:7-alpine
    command: redis-server --save "" --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - simulados_net

networks:
  simulados_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: simulados_br
    ipam:
      config:
        - subnet: 172.22.0.0/16

volumes:
  nginx_ssl:
    driver: local
  nginx_cache:
    driver: local