services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    expose:
      - 5000
    volumes:
      - ./backend/user_data:/app/user_data
    networks:
      - simulados_net

  frontend:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "10443:443"
      - "10080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/nginx/auth/.htpasswd:/etc/nginx/auth/.htpasswd:ro
      - nginx_ssl:/etc/nginx/ssl
    depends_on:
      - backend
    # --- COMANDO CORRIGIDO ---
    # O comando openssl agora está em uma única linha para evitar erros de parsing do shell.
    command: >
      sh -c "
        apk add --no-cache openssl &&
        if [ ! -f /etc/nginx/ssl/privkey.pem ]; then
          echo 'Gerando certificados SSL autoassinados...';
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/privkey.pem -out /etc/nginx/ssl/fullchain.pem -subj '/CN=localhost';
          echo 'Certificados gerados com sucesso.';
        else
          echo 'Certificados SSL já existem.';
        fi &&
        nginx -g 'daemon off;'
      "
    networks:
      - simulados_net

networks:
  simulados_net:
    driver: bridge

volumes:
  nginx_ssl: